package io.musika.notifier.domain.model.shared.kernel;

import io.musika.notifier.domain.model.shared.ValueObject;

import java.io.Serializable;

import static org.apache.commons.lang3.Validate.notNull;

/**
 * Uniquely identifies a particular track. Automatically generated by the application.
 *
 * @author Sylvain Lecoy <sylvain.lecoy@gmail.com>
 */
public final class TrackId implements ValueObject<TrackId>, Serializable {

	private String id;

	public TrackId(final String id) {
		notNull(id);

		this.id = id;
	}

	public String idString() {
	    return id;
    }

	@Override
	public boolean equals(Object o) {
		if (this == o) return true;
		if (o == null || getClass() != o.getClass()) return false;

		TrackId other = (TrackId) o;

		return sameValueAs(other);
	}

	@Override
	public int hashCode() {
		return id.hashCode();
	}

	@Override
	public boolean sameValueAs(final TrackId other) {
		return other != null && this.id.equals(other.id);
	}

	@Override
	public String toString() {
		return id;
	}

	protected TrackId() {
		// Needed by Hibernate
	}

}
